on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y \
            build-essential \
            git \
            cmake \
            g++ \
            zlib1g-dev \
            libssl-dev \
            libreadline-dev \
            libffi-dev \
            gperf \
            ninja-build \
            pkg-config\
            make\
            git \
            zlib1g-dev\
            libssl-dev gperf cmake clang-14 \
            libc++-14-dev \
            libc++abi-14-dev

      - name: Set version
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            VERSION="git-${GITHUB_SHA::8}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Configure & build
        run: |
          ls
          rm -rf build
          mkdir -p build
          cd build
          ls
          CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
          cmake --build .
          cd build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: ../telegram-bot-api
           asset_name: telegram-bot-api
           tag: ${{ github.ref }}
           overwrite: true
           body: "This is new release"
